### ISSUE TITLE
Error: ENOENT on any slate command

### ISSUE THREAD

**Issue by jpicao** [Shopify/slate#1049]
Im new in using slate but i followed the guidelines on installing slate V 0, right now im getting this message when i try any slate command

fs.js:145
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\John\Documents\JOB FILES\plushland\public\node_modules\@shopify\slate-tools\lib\commands'
    at fs.readdirSync (fs.js:895:3)
    at Object.<anonymous> (C:\Users\John\AppData\Roaming\npm\node_modules\@shopify\slate\lib\index.js:93:23)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)

im currently running 
Gulp 
CLI version: 2.2.0
Local version: 3.9.0
node v10.4.1

**Comment by jonathanmoore** [comment]
It sounds like you're using too new of a version of node. When working on a v.0 project I always roll back to Node 6.11.5—it might be excessively low, but I know it works.

**Comment by Maurice-JB** [comment]
If downgrading doesn't work, a colleague who recently encountered this issue for hours ended up reinstalling npm, yarn and node and that fixed it. No idea exactly which one did it ultimately 🤷🏻‍♂️

**Comment by Maurice-JB** [comment]
Just an additional note if anyone else is struggling with this. If you're behind a corporate firewall that injects certs, it can play havoc with npm/yarn. Try hotspotting instead.
