### ISSUE TITLE
Unhandled Promise Reject Warning

### ISSUE THREAD

**Issue by noctivityinc** [Shopify/slate#1077]
### Problem

When starting yarn, I get an UnhandledPromiseRejectionWarning.

### Replication steps

Start yarn watch or yarn start

### More Information

Here is the error:

(node:67572) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
    at createError (/Users/jlippiner/Dropbox/Projects/fruitstand/fs-bootstrap/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/jlippiner/Dropbox/Projects/fruitstand/fs-bootstrap/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/Users/jlippiner/Dropbox/Projects/fruitstand/fs-bootstrap/node_modules/axios/lib/adapters/http.js:202:11)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(no

**Comment by Maurice-JB** [comment]
Duplicates #1075 
Does not affect workflow, just a visual annoyance when running slate.

**Comment by noctivityinc** [comment]
Just workflow.  Thanks.

**Comment by noctivityinc** [comment]
Sorry I meant just visual.
