### ISSUE TITLE
slate build results in error

### ISSUE THREAD

**Issue by mime0n** [Shopify/slate#295]
### Problem

I am working on Windows 10 via Bash on Windows. I ran `slate build` in a newly created project and ran into this error. 

```
/mnt/c/Users/mime0n/Desktop/mime0n-shop/node_modules/dev-ip/lib/dev-ip.js:21
    var networkInterfaces = require("os").networkInterfaces();
                                          ^

Error: EINVAL: invalid argument, uv_interface_addresses
    at Error (native)
    at getIp (/mnt/c/Users/mime0n/Desktop/mime0n-shop/node_modules/dev-ip/lib/dev-ip.js:21:43)
    at Object.<anonymous> (/mnt/c/Users/mime0n/Desktop/mime0n-shop/node_modules/browser-sync/l
ib/utils.js:4:38)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/c/Users/mime0n/Desktop/mime0n-shop/node_modules/browser-sync/l
ib/snippet.js:9:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by t-kelly** [comment]
Thanks @mime0n -- We'll look into this and get back to you.

**Comment by moe2566** [comment]
Might be related, [/mnt with EINVAL for lstat](https://github.com/Microsoft/BashOnWindows/issues/2448)

**Comment by lloydstubber** [comment]
Did you find a workaround for this @mime0n ? I can't even seem to create a theme without my WSL throwing an issue - see [here](https://github.com/Shopify/slate/issues/352).

**Comment by lloydstubber** [comment]
@mime0n Have you tried apt-get update/upgrade on the WSL lately and retried the build? It seemed to fix my issue when creating new themes with Slate.
