### ISSUE TITLE
Error getting JS to minfiy in slate build

### ISSUE THREAD

**Issue by adamrasheed** [Shopify/slate#299]
### Problem
When I run slate (specifically, type the command 'slate start'), I get this error in my terminal:

GulpUglifyError: unable to minify JavaScript
Caused by: SyntaxError: Unexpected token: operator (=) (line: 4, col: 1, pos: 29)

```
Error
    at new JS_Parse_Error (eval at <anonymous> (/Users/adamrasheed/Dropbox/Client-Projects/20170410-FlexRake/Website/flexrake-theme/node_modules/@shopify/slate-tools/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1545:18)
    at js_error (eval at <anonymous> (/Users/adamrasheed/Dropbox/Client-Projects/20170410-FlexRake/Website/flexrake-theme/node_modules/@shopify/slate-tools/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1553:11)
    at croak (eval at <anonymous> (/Users/adamrasheed/Dropbox/Client-Projects/20170410-FlexRake/Website/flexrake-theme/node_modules/@shopify/slate-tools/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2089:9)
    at token_error (eval at <anonymous> (/Users/adamrasheed/Dropbox/Client-Projects/20170410-FlexRake/Website/flexrake-theme/node_modules/@shopify/slate-tools/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2097:9)
    at unexpected (eval at <anonymous> (/Users/adamrasheed/Dropbox/Client-Projects/20170410-FlexRake/Website/flexrake-theme/node_modules/@shopify/slate-tools/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2103:9)
    at expr_atom (eval at <anonymous> (/Users/adamrasheed/Dropbox/Client-Projects/20170410-FlexRake/Website/flexrake-theme/node_modules/@shopify/slate-tools/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2630:9)
    at maybe_unary (eval at <anonymous> (/Users/adamrasheed/Dropbox/Client-Projects/20170410-FlexRake/Website/flexrake-theme/node_modules/@shopify/slate-tools/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2792:19)
    at expr_ops (eval at <anonymous> (/Users/adamrasheed/Dropbox/Client-Projects/20170410-FlexRake/Website/flexrake-theme/node_modules/@shopify/slate-tools/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2827:24)
    at maybe_conditional (eval at <anonymous> (/Users/adamrasheed/Dropbox/Client-Projects/20170410-FlexRake/Website/flexrake-theme/node_modules/@shopify/slate-tools/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2832:20)
    at maybe_assign (eval at <anonymous> (/Users/adamrasheed/Dropbox/Client-Projects/20170410-FlexRake/Website/flexrake-theme/node_modules/@shopify/slate-tools/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2856:20)
    at expression (eval at <anonymous> (/Users/adamrasheed/Dropbox/Client-Projects/20170410-FlexRake/Website/flexrake-theme/node_modules/@shopify/slate-tools/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2875:20)
    at simple_statement (eval at <anonymous> (/Users/adamrasheed/Dropbox/Client-Projects/20170410-FlexRake/Website/flexrake-theme/node_modules/@shopify/slate-tools/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2314:55)
    at eval (eval at <anonymous> (/Users/adamrasheed/Dropbox/Client-Projects/20170410-FlexRake/Website/flexrake-theme/node_modules/@shopify/slate-tools/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2178:20)
    at eval (eval at <anonymous> (/Users/adamrasheed/Dropbox/Client-Projects/20170410-FlexRake/Website/flexrake-theme/node_modules/@shopify/slate-tools/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2136:24)
    at eval (eval at <anonymous> (/Users/adamrasheed/Dropbox/Client-Projects/20170410-FlexRake/Website/flexrake-theme/node_modules/@shopify/slate-tools/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2904:23)
    at Object.parse (eval at <anonymous> (/Users/adamrasheed/Dropbox/Client-Projects/20170410-FlexRake/Website/flexrake-theme/node_modules/@shopify/slate-tools/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2915:7)
```
The server still runs, but I can't get any of my javascript files to run.

### Replication steps

Not sure how you could replicate this?

### More Information

How can I fix this?

**Comment by t-kelly** [comment]
I'm assuming this is not a fresh install? Looks like you have a syntax error somewhere in your JS.

**Comment by adamrasheed** [comment]
Not a fresh install and its giving me errors in the node_modules folder. How do I rebuild them correctly?

**Comment by t-kelly** [comment]
Are you `require`'ing or `import`ing a library from node_modules?  Our tooling currently doesn't support anything like that. You will need to include the JS files in the `scripts/vendors` folder.

Otherwise, the only thing I can recommend given the information you've provided here is to remove any edits you've done since installing Slate and seeing which edit causes the error. 

Closing because this is a project specific problem, not a Slate problem. Please feel free to continue to post here with any additional questions and updates!

**Comment by walkerrandolphsmith** [comment]
Is there a way to capture a better error message containing information about the line number and file path that contains a syntax error? I'll investigate the issue, but would love pointers if you already have ideas.

**Comment by walkerrandolphsmith** [comment]
A quick and non-configurable way is to
```js
return gulp.src(libs.concat(scripts))
    .pipe(concat('all.js'))
    .pipe(gulpif(COMPRESS, uglify().on('error', console.log)))
    .pipe(gulp.dest('./build/javascripts'));
```
