### ISSUE TITLE
Slate Deploy gives, Error: ENOENT: no such file or directory, uv_cwd

### ISSUE THREAD

**Issue by alan-brennan** [Shopify/slate#316]
### Problem

slate deploy
path.js:1149
          cwd = process.cwd();
                        ^

Error: ENOENT: no such file or directory, uv_cwd
    at Error (native)
    at Object.resolve (path.js:1149:25)
    at Function.Module._resolveLookupPaths (module.js:390:17)
    at Function.Module._resolveFilename (module.js:460:31)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/@shopify/slate/lib/index.js:26:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

### Replication steps

1. slate build
2. upload the theme manually (from within shopify)
3. created a private app
4. edited config.yml
5. slate deploy .....causes the above error

### More Information

sorry not very experienced with node.js so can't add anymore here

**Comment by alan-brennan** [comment]
sorry just noticed my error. closing this
