### ISSUE TITLE
Unable to use slate node 6.10.0

### ISSUE THREAD

**Issue by juanpasolano** [Shopify/slate#341]
### Problem

Unable to use slate commands

### Replication steps

node -v 6.10.0
npm -v 5.5.1

1. `npm install -g @shopify/slate` install slate glbally
2. create new project `slate theme new-theme`
3. cd to `/new-theme`
4. run `slate`or any other `slate [command]`

5. try `npm install` on the theme folder as of #333  (still same result)

### More Information
Returns
```
$ slate
fs.js:951
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/Users/juanpablosolano/Desktop/jaggrills/node_modules/@shopify/slate-tools/lib/commands'
    at Error (native)
    at fs.readdirSync (fs.js:951:18)
    at Object.<anonymous> (/Users/juanpablosolano/.nvm/versions/node/v6.10.0/lib/node_modules/@shopify/slate/lib/index.js:93:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
```

**Comment by iamkeir** [comment]
@juanpasolano did you close this because you were able to resolve it? If so, please post the outcome as it can be useful for others :)

**Comment by aeu** [comment]
I am having this exact problem.

node -v 8.9.4
npm -v 5.6.0

Can't even run slate -v in the created theme dir

**Comment by mattkersner** [comment]
Having this issue, anyone find a solution?
