### ISSUE TITLE
Trouble Installing Slate via the WSL

### ISSUE THREAD

**Issue by lloydstubber** [Shopify/slate#352]
### Problem

Can't create theme when using `slate theme <theme name>`. Getting this error below:

```
slate theme heimur

  This may take some time...

  ✔ slate-theme download completed
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

> fsevents@1.1.3 install /mnt/c/Users/LL COOL J/Desktop/heimur/node_modules/fsevents
> node install


> @shopify/themekit@0.6.6 postinstall /mnt/c/Users/LL COOL J/Desktop/heimur/node_modules/@shopify/themekit
> node ./lib/cli.js install

|/mnt/c/Users/LL COOL J/Desktop/heimur/node_modules/@shopify/themekit/lib/install.js:46
        throw runErr;

Error: The `/mnt/c/Users/LL COOL J/Desktop/heimur/node_modules/@shopify/themekit/bin/theme` binary doesn't seem to work correctly
    at BinWrapper.<anonymous> (/mnt/c/Users/LL COOL J/Desktop/heimur/node_modules/bin-wrapper/index.js:156:7)
    at ChildProcess.<anonymous> (/mnt/c/Users/LL COOL J/Desktop/heimur/node_modules/bin-check/index.js:26:4)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
npm WARN heimur@0.0.1 No description
npm WARN heimur@0.0.1 No repository field.
npm WARN heimur@0.0.1 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @shopify/themekit@0.6.6 postinstall: `node ./lib/cli.js install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @shopify/themekit@0.6.6 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/s1dney/.npm/_logs/2017-11-20T01_24_55_978Z-debug.log
  ✔ devDependencies installed
  ✔ heimur theme is ready
```

### Replication steps

OS: Windows 10
Shell: Windows Subsytem for Linux
npm: 5.0.0 (tried 3.8.6 and same issue)
Node: 8.0.0 (tried 6.0.0 and same issue)

### More Information

Is this possibly due to using the WSL? Had a couple hiccups when trying just Themekit - see [fix here](https://github.com/lloydstubber/My-WSL-Setup#shopify-themekit).

Any help would be muchly appreciated!

**Comment by lloydstubber** [comment]
After doing a recent update via the WSL this seems to work perfectly now. Creating a theme and using `slate start` works a treat. It just doesn't like `xdg-open` as the WSL has no browser to open. The link can be pasted into the browser and hot-reloading works so I'll close this. Thanks!

**Comment by lloydstubber** [comment]
FYI updating the WSL caused this error to happen again. This is obviously a WSL breaking issue rather than Slate. Just a note for those in the same boat as me, it'll work fine if using Yarn to run the package managing: `slate theme my-theme --yarn`
