### ISSUE TITLE
Slate v0.13.0 commands creating wrong dev dependency in package.json

### ISSUE THREAD

**Issue by mattkersner** [Shopify/slate#544]
### Problem

When running the slate migrate or slate theme new-theme-name commands, the package.json file that is created has a dev dependency of @shopify/slate-tools: 1.0.0-beta and this is causing all slate commands to not work. 

### Replication steps

Run slate theme new-theme-name or slate migrate on an existing theme in CLI, cd into new theme directory. Try to run slate build and receive error. Open package.json and see the @shopify/slate-tools dev dependency is pointing to the wrong version of slate. Change the version to @shopify/slate-tools: 0.13.0 and run npm install. Moving forward all the commands will work as they should. 

### More Information

node -v: 8.6.0
slate -v: 0.13.0
npm -v: 6.0.0
macOS High Sierra: 10.13.4

**Comment by shoshanna** [comment]
Does anyone have a detailed walkthrough on how to get v.0 set up after fixing the dependency in package.json? 

I've tried to get the correct_node modules installed after making that change, but I'm doing it in the wrong order or from the wrong directory somehow. Everything I try throws errors.

I see that this has been fixed in 0.14.0. Sorry for the basic questions, but I'm not sure how to get Slate to install as 0.14.0 (not v. 1.0)? I also want to make sure that if I update to 0.14.0 it won't cause issues with my existing 0.13.0 project?

Here's what I've tried so far.

I've updated the dependency in package.json to "@shopify/slate-tools": "0.13.0".
cd my-custom-theme
npm install

<pre>
npm WARN deprecated gulp-util@3.0.7: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

npm WARN deprecated gulp-util@2.2.20: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js

npm WARN deprecated express@2.5.11: express 2.x series is deprecated

npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130

npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

npm WARN deprecated connect@1.9.2: connect 1.x series is deprecated

npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js

WARN tar ENOENT: no such file or directory, open '/Users/shoshanna/Dropbox/Documents/Work/Shared Clients/client-name/Shopify theme/my-custom-theme/node_modules/.staging/glob-62e886e1/package.json'

WARN tar ENOENT: no such file or directory, open '/Users/shoshanna/Dropbox/Documents/Work/Shared Clients/client-name/Shopify theme/my-custom-theme/node_modules/.staging/glob-62e886e1/README.md'

WARN tar ENOENT: no such file or directory, open '/Users/shoshanna/Dropbox/Documents/Work/Shared Clients/client-name/Shopify theme/my-custom-theme/node_modules/.staging/glob-62e886e1/LICENSE'

WARN tar ENOENT: no such file or directory, open '/Users/shoshanna/Dropbox/Documents/Work/Shared Clients/client-name/Shopify theme/my-custom-theme/node_modules/.staging/glob-62e886e1/common.js'

WARN tar ENOENT: no such file or directory, open '/Users/shoshanna/Dropbox/Documents/Work/Shared Clients/client-name/Shopify theme/my-custom-theme/node_modules/.staging/glob-62e886e1/glob.js'

WARN tar ENOENT: no such file or directory, open '/Users/shoshanna/Dropbox/Documents/Work/Shared Clients/client-name/Shopify theme/my-custom-theme/node_modules/.staging/glob-62e886e1/sync.js'

WARN tar ENOENT: no such file or directory, open '/Users/shoshanna/Dropbox/Documents/Work/Shared Clients/client-name/Shopify theme/my-custom-theme/node_modules/.staging/glob-62e886e1/changelog.md'

npm WARN my-custom-theme@0.0.1 No description

npm WARN my-custom-theme@0.0.1 No repository field.

npm WARN my-custom-theme@0.0.1 No license field.



npm ERR! code E404

npm ERR! 404 Not Found: natives@https://registry.npmjs.org/natives/-/natives-1.1.4.tgz
</pre>

I then tried copying node_modules from a working project.

Once I've done that, these commands work:
slate -v
slate deploy -m

However, I get this on slate watch:

<pre>
module.js:557

    throw err;

    ^



Error: Cannot find module '../lib/completion'

    at Function.Module._resolveFilename (module.js:555:15)

    at Function.Module._load (module.js:482:25)

    at Module.require (module.js:604:17)

    at require (internal/module.js:11:18)

    at Object.<anonymous> (/Users/shoshanna/Dropbox/Documents/Work/Shared Clients/client-name/Shopify theme/my-custom-theme/node_modules/.bin/gulp:13:18)

    at Module._compile (module.js:660:30)

    at Object.Module._extensions..js (module.js:671:10)

    at Module.load (module.js:573:32)

    at tryModuleLoad (module.js:513:12)

    at Function.Module._load (module.js:505:3)

Shoshannas-MacBook-Pro:my-custom-theme shoshanna$ slate watch

module.js:557

    throw err;

    ^



Error: Cannot find module '../lib/completion'

    at Function.Module._resolveFilename (module.js:555:15)

    at Function.Module._load (module.js:482:25)

    at Module.require (module.js:604:17)

    at require (internal/module.js:11:18)

    at Object.<anonymous> (/Users/shoshanna/Dropbox/Documents/Work/Shared Clients/client-name/Shopify theme/my-custom-theme/node_modules/.bin/gulp:13:18)

    at Module._compile (module.js:660:30)

    at Object.Module._extensions..js (module.js:671:10)

    at Module.load (module.js:573:32)

    at tryModuleLoad (module.js:513:12)

    at Function.Module._load (module.js:505:3)
</pre>

slate -v
0.13.0

node -v
v9.4.0

npm -v 
5.6.0

I would really appreciate any help. Thank you!
