### ISSUE TITLE
Weird bug with nvm

### ISSUE THREAD

**Issue by magpiedigital** [Shopify/slate#561]
### Problem

When I run `npm start` for the first time on a new theme, everything seems to work fine. However, if I kill the program and then run `npm start` again, I get this:

```
> starter-theme@1.0.0-alpha.1 start /Users/hamishjohnson/Documents/Magpie Digital/Web Development/shopify themes/cardell-media
> slate-tools start

(node:13128) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Server.setupListenHandle [as _listen2] (net.js:1330:14)
    at listenInCluster (net.js:1378:12)
    at Server.listen (net.js:1466:7)
    at DevServer.start (/Users/hamishjohnson/Documents/Magpie Digital/Web Development/shopify themes/cardell-media/node_modules/@shopify/slate-tools/tools/dev-server/index.js:35:17)
    at Object.<anonymous> (/Users/hamishjohnson/Documents/Magpie Digital/Web Development/shopify themes/cardell-media/node_modules/@shopify/slate-tools/cli/commands/start.js:151:11)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:576:3)
Emitted 'error' event at:
    at emitErrorNT (net.js:1357:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:721:11)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:576:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! starter-theme@1.0.0-alpha.1 start: `slate-tools start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the starter-theme@1.0.0-alpha.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hamishjohnson/.npm/_logs/2018-05-16T15_37_13_619Z-debug.log
```

Somehow I've found out I can fix this by executing `source ~/.nvm/nvm.sh` and then executing `npm start` again.

**Comment by t-kelly** [comment]
Huh weird... it's like the process isn't being killed. Will keep an eye out for this, thanks!

**Comment by magpiedigital** [comment]
I have those lines in my `.bashrc`

**Comment by magpiedigital** [comment]
*hangs head in shame*

Turns out I've been using `ctrl + z`, not `ctrl + c`.

**Comment by chrisberthe** [comment]
That would do it 😛glad you solved the issue @magpiedigital!
