### ISSUE TITLE
Node 10 - yarn create slate-theme fails on node dependency conflict

### ISSUE THREAD

**Issue by kryali** [Shopify/slate#595]
### Problem

yarn create slate-theme fails on node dependency conflict #595

```
Development $ yarn create slate-theme shopify-project
yarn create v1.7.0
[1/4] 🔍  Resolving packages...
⠁ (node:98211) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Installed "create-slate-theme@1.0.0-beta.2" with binaries:
      - create-slate-theme
[#########################################################################################] 136/136
Creating a new Slate theme in: /Users/uho/Development/shopify-slate.
Cloning theme from a git repo: https://github.com/shopify/starter-theme.git
Installing theme dependencies...
yarn install v1.7.0
[1/4] 🔍  Resolving packages...
⠁ (node:98219) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[2/4] 🚚  Fetching packages...
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
(node:98212) UnhandledPromiseRejectionWarning: Error: Command failed: yarnpkg
    at makeError (/Users/uho/.config/yarn/global/node_modules/execa/index.js:169:9)
    at Promise.all.then.arr (/Users/uho/.config/yarn/global/node_modules/execa/index.js:274:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:98212) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:98212) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 4.04s.
```

```
shopify-project $ yarn install
yarn install v1.7.0
[1/4] 🔍  Resolving packages...
⠁ (node:98197) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[2/4] 🚚  Fetching packages...
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
### More Information

*Any additional information which might be helpful.*

**Comment by kryali** [comment]
workaround with `--ignore-engines`

**Comment by kryali** [comment]
wow these tools and documentation are bad and hard to use

**Comment by kryali** [comment]
![image](https://user-images.githubusercontent.com/174889/40561394-f22888e2-6011-11e8-9214-82fd728db0ca.png)

**Comment by kryali** [comment]
https://localhost:8080 renders error

```
Cannot GET /
```

**Comment by chrisberthe** [comment]
Hi @kryali, you've stated two separate issues here. For the first, can you run `node -v` and let us know what version of Node you're currently running? 

As for `Cannot GET/`, I'll redirect you to [this comment](https://github.com/Shopify/slate/issues/518#issuecomment-386632878) that has already addressed this. We are looking into ways we can address the confusion around this, but for now realize that what you're seeing is normal if accessing `localhost` directly.

**Comment by kryali** [comment]
Hey @chrisberthe, appreciate the help. Here is my node version below.

```
node -v
v10.2.1
```

Agree that the documentation could be much better here.

**Comment by chrisberthe** [comment]
Could you test with the current `8.11.2` LTS version and see if that solves the issue and report back?

**Comment by kryali** [comment]
Is there a handy way to change node versions? Don't know a whole lot about node version management, sorry.

**Comment by lloydstubber** [comment]
Have a look at [nvm](https://github.com/creationix/nvm) @kryali

**Comment by kryali** [comment]
things look good on 8.11.2

```
Development $ node --version
v8.11.2
Development $ yarn create slate-theme shopify-project
yarn create v1.7.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Installed "create-slate-theme@1.0.0-beta.2" with binaries:
      - create-slate-theme
[########################################################################################################################################] 136/136
Creating a new Slate theme in: /Users/uho/Development/shopify-project.
Cloning theme from a git repo: https://github.com/shopify/starter-theme.git
Installing theme dependencies...
yarn install v1.7.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "@shopify/slate-tools > babel-loader@7.1.4" has unmet peer dependency "babel-core@6".
warning "@shopify/slate-tools > stylelint-webpack-plugin@0.10.3" has incorrect peer dependency "stylelint@^8.0.0".
warning "@shopify/slate-tools > stylelint-webpack-plugin@0.10.3" has incorrect peer dependency "webpack@^3 || ^2 || ^2.2.0-rc.0 || ^2.1.0-beta.0 || ^1.13.2".
warning "@shopify/slate-tools > webpack-dev-middleware@1.10.2" has incorrect peer dependency "webpack@1 || ^2.1.0-beta || ^2.2.0-rc.0".
warning "babel-preset-shopify > react-hot-loader > redbox-react@1.5.0" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0-beta || ^16.0.0".
warning "babel-preset-shopify > react-hot-loader > redbox-react@1.5.0" has unmet peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16.0.0-beta || ^16.0.0".
warning " > eslint-plugin-shopify@19.0.1" has unmet peer dependency "eslint@<5 >=4.7.1".
warning "eslint-plugin-shopify > eslint-config-prettier@2.9.0" has unmet peer dependency "eslint@>=3.14.1".
warning "eslint-plugin-shopify > eslint-plugin-ava@4.5.1" has unmet peer dependency "eslint@>=3.6".
warning "eslint-plugin-shopify > eslint-plugin-babel@4.1.2" has unmet peer dependency "eslint@>=3.0.0".
warning "eslint-plugin-shopify > eslint-plugin-flowtype@2.46.1" has unmet peer dependency "eslint@>=2.0.0".
warning "eslint-plugin-shopify > eslint-plugin-jest@21.14.1" has unmet peer dependency "eslint@>=3.6".
warning "eslint-plugin-shopify > eslint-plugin-jsx-a11y@6.0.3" has unmet peer dependency "eslint@^3 || ^4".
warning "eslint-plugin-shopify > eslint-plugin-lodash@2.6.1" has unmet peer dependency "eslint@>=2.10.0".
warning "eslint-plugin-shopify > eslint-plugin-mocha@4.12.1" has unmet peer dependency "eslint@^2.0.0 || ^3.0.0 || ^4.0.0".
warning "eslint-plugin-shopify > eslint-plugin-node@5.2.1" has unmet peer dependency "eslint@>=3.1.0".
warning "eslint-plugin-shopify > eslint-plugin-react@7.7.0" has unmet peer dependency "eslint@^3.0.0 || ^4.0.0".
warning "eslint-plugin-shopify > eslint-plugin-sort-class-members@1.3.0" has unmet peer dependency "eslint@>=0.8.0".
warning "eslint-plugin-shopify > typescript-eslint-parser@11.0.0" has unmet peer dependency "typescript@*".
warning " > stylelint-config-shopify@5.0.0" has unmet peer dependency "stylelint@>=9.0".
warning "stylelint-config-shopify > stylelint-order@0.8.1" has unmet peer dependency "stylelint@^8.0.0 || ^9.0.0".
warning "stylelint-config-shopify > stylelint-scss@2.5.0" has unmet peer dependency "stylelint@^8.0.0 || ^9.0.0".
[4/4] 📃  Building fresh packages...
✨  Done in 13.60s.
✨  Done in 16.21s.
Development $
```

**Comment by t-kelly** [comment]
Just tried this on v10.4.1, doesn't seem to be an issue anymore?
