### ISSUE TITLE
Unable to use existing debut theme on slate

### ISSUE THREAD

**Issue by we18** [Shopify/slate#624]
I am using Latest version of slate.
my store is using `debut` theme. I downloaded the code of theme using `theme-kit`. and then I used following command to generate theme
```
yarn create slate-theme my-new-theme
```
I replaced content of `src` folder to my theme files (debut, which i downloaded from themekit).
When I do `yarn start`, It give me lots of error.

```
Failed to compile.

undefined
./layout/theme.liquid
Module not found: Error: Can't resolve './extra.css' in '/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/src/layout'
 @ ./layout/theme.liquid
 @ . sync ^\.\/layout.*\.liquid$
 @ ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js
 @ multi ../node_modules/@shopify/slate-tools/tools/webpack/hot-client.js ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js

./layout/gift_card.liquid
Module not found: Error: Can't resolve './gift-card.js' in '/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/src/layout'
 @ ./layout/gift_card.liquid
 @ . sync ^\.\/layout.*\.liquid$
 @ ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js
 @ multi ../node_modules/@shopify/slate-tools/tools/webpack/hot-client.js ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js

./layout/gift_card.liquid
Module not found: Error: Can't resolve './gift-card.js' in '/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/src/layout'
 @ ./layout/gift_card.liquid
 @ . sync ^\.\/layout.*\.liquid$
 @ ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js
 @ multi ../node_modules/@shopify/slate-tools/tools/webpack/hot-client.js ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js

./layout/gift_card.liquid
Module not found: Error: Can't resolve './gift-card.scss.css' in '/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/src/layout'
 @ ./layout/gift_card.liquid
 @ . sync ^\.\/layout.*\.liquid$
 @ ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js
 @ multi ../node_modules/@shopify/slate-tools/tools/webpack/hot-client.js ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js

./layout/theme.liquid
Module not found: Error: Can't resolve './lazysizes.js' in '/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/src/layout'
 @ ./layout/theme.liquid
 @ . sync ^\.\/layout.*\.liquid$
 @ ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js
 @ multi ../node_modules/@shopify/slate-tools/tools/webpack/hot-client.js ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js

./layout/theme.liquid
Module not found: Error: Can't resolve './lazysizes.min.js' in '/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/src/layout'
 @ ./layout/theme.liquid
 @ . sync ^\.\/layout.*\.liquid$
 @ ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js
 @ multi ../node_modules/@shopify/slate-tools/tools/webpack/hot-client.js ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js

./layout/password.liquid
Module not found: Error: Can't resolve './match-media.min.js' in '/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/src/layout'
 @ ./layout/password.liquid
 @ . sync ^\.\/layout.*\.liquid$
 @ ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js
 @ multi ../node_modules/@shopify/slate-tools/tools/webpack/hot-client.js ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js

./layout/theme.liquid
Module not found: Error: Can't resolve './match-media.min.js' in '/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/src/layout'
 @ ./layout/theme.liquid
 @ . sync ^\.\/layout.*\.liquid$
 @ ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js
 @ multi ../node_modules/@shopify/slate-tools/tools/webpack/hot-client.js ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js

./layout/password.liquid
Module not found: Error: Can't resolve './password.js' in '/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/src/layout'
 @ ./layout/password.liquid
 @ . sync ^\.\/layout.*\.liquid$
 @ ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js
 @ multi ../node_modules/@shopify/slate-tools/tools/webpack/hot-client.js ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js

./layout/password.liquid
Module not found: Error: Can't resolve './password.js' in '/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/src/layout'
 @ ./layout/password.liquid
 @ . sync ^\.\/layout.*\.liquid$
 @ ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js
 @ multi ../node_modules/@shopify/slate-tools/tools/webpack/hot-client.js ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js

./layout/password.liquid
Module not found: Error: Can't resolve './theme.js' in '/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/src/layout'
 @ ./layout/password.liquid
 @ . sync ^\.\/layout.*\.liquid$
 @ ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js
 @ multi ../node_modules/@shopify/slate-tools/tools/webpack/hot-client.js ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js

./layout/theme.liquid
Module not found: Error: Can't resolve './theme.js' in '/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/src/layout'
 @ ./layout/theme.liquid
 @ . sync ^\.\/layout.*\.liquid$
 @ ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js
 @ multi ../node_modules/@shopify/slate-tools/tools/webpack/hot-client.js ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js

./layout/theme.liquid
Module not found: Error: Can't resolve './theme.js' in '/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/src/layout'
 @ ./layout/theme.liquid
 @ . sync ^\.\/layout.*\.liquid$
 @ ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js
 @ multi ../node_modules/@shopify/slate-tools/tools/webpack/hot-client.js ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js

./layout/password.liquid
Module not found: Error: Can't resolve './theme.js' in '/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/src/layout'
 @ ./layout/password.liquid
 @ . sync ^\.\/layout.*\.liquid$
 @ ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js
 @ multi ../node_modules/@shopify/slate-tools/tools/webpack/hot-client.js ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js

./layout/password.liquid
Module not found: Error: Can't resolve './theme.scss.css' in '/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/src/layout'
 @ ./layout/password.liquid
 @ . sync ^\.\/layout.*\.liquid$
 @ ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js
 @ multi ../node_modules/@shopify/slate-tools/tools/webpack/hot-client.js ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js

./layout/theme.liquid
Module not found: Error: Can't resolve './theme.scss.css' in '/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/src/layout'
 @ ./layout/theme.liquid
 @ . sync ^\.\/layout.*\.liquid$
 @ ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js
 @ multi ../node_modules/@shopify/slate-tools/tools/webpack/hot-client.js ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js

./layout/gift_card.liquid
Module not found: Error: Can't resolve './theme.scss.css' in '/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/src/layout'
 @ ./layout/gift_card.liquid
 @ . sync ^\.\/layout.*\.liquid$
 @ ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js
 @ multi ../node_modules/@shopify/slate-tools/tools/webpack/hot-client.js ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js

./layout/theme.liquid
Module not found: Error: Can't resolve './vendor.js' in '/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/src/layout'
 @ ./layout/theme.liquid
 @ . sync ^\.\/layout.*\.liquid$
 @ ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js
 @ multi ../node_modules/@shopify/slate-tools/tools/webpack/hot-client.js ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js

./layout/theme.liquid
Module not found: Error: Can't resolve './vendor.js' in '/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/src/layout'
 @ ./layout/theme.liquid
 @ . sync ^\.\/layout.*\.liquid$
 @ ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js
 @ multi ../node_modules/@shopify/slate-tools/tools/webpack/hot-client.js ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js

./layout/gift_card.liquid
Module not found: Error: Can't resolve './vendor.js' in '/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/src/layout'
 @ ./layout/gift_card.liquid
 @ . sync ^\.\/layout.*\.liquid$
 @ ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js
 @ multi ../node_modules/@shopify/slate-tools/tools/webpack/hot-client.js ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js

./layout/gift_card.liquid
Module not found: Error: Can't resolve './vendor.js' in '/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/src/layout'
 @ ./layout/gift_card.liquid
 @ . sync ^\.\/layout.*\.liquid$
 @ ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js
 @ multi ../node_modules/@shopify/slate-tools/tools/webpack/hot-client.js ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js

./layout/password.liquid
Module not found: Error: Can't resolve './vendor.js' in '/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/src/layout'
 @ ./layout/password.liquid
 @ . sync ^\.\/layout.*\.liquid$
 @ ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js
 @ multi ../node_modules/@shopify/slate-tools/tools/webpack/hot-client.js ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js

./layout/password.liquid
Module not found: Error: Can't resolve './vendor.js' in '/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/src/layout'
 @ ./layout/password.liquid
 @ . sync ^\.\/layout.*\.liquid$
 @ ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js
 @ multi ../node_modules/@shopify/slate-tools/tools/webpack/hot-client.js ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js

../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js
Module not found: Error: Can't resolve '__appstatic__' in '/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/@shopify/slate-tools/tools/webpack'
 @ ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js 31:0-38
 @ multi ../node_modules/@shopify/slate-tools/tools/webpack/hot-client.js ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js

[copy-webpack-plugin] unable to locate '/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/src/assets/svg' at '/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/src/assets/svg'

Compiled with warnings.

./layout/password.liquid
Module build failed: ModuleNotFoundError: Module not found: Error: Can't resolve './theme.scss.css' in '/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/src/layout'
    at factory.create (/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/webpack/lib/Compilation.js:522:10)
    at factory (/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/webpack/lib/NormalModuleFactory.js:358:22)
    at resolver (/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/webpack/lib/NormalModuleFactory.js:118:21)
    at asyncLib.parallel (/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/webpack/lib/NormalModuleFactory.js:198:22)
    at /Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/neo-async/async.js:2817:7
    at /Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/neo-async/async.js:6783:13
    at normalResolver.resolve (/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/webpack/lib/NormalModuleFactory.js:188:25)
    at doResolve (/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/enhanced-resolve/lib/Resolver.js:181:12)
    at hook.callAsync (/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/enhanced-resolve/lib/Resolver.js:232:5)
    at _fn0 (eval at create (/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at resolver.doResolve (/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
    at hook.callAsync (/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/enhanced-resolve/lib/Resolver.js:232:5)
    at _fn0 (eval at create (/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at hook.callAsync (/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/enhanced-resolve/lib/Resolver.js:232:5)
    at _fn0 (eval at create (/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:12:1)
    at resolver.doResolve (/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
 @ . sync ^\.\/layout.*\.liquid$
 @ ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js
 @ multi ../node_modules/@shopify/slate-tools/tools/webpack/hot-client.js ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js

./layout/gift_card.liquid
Module build failed: ModuleNotFoundError: Module not found: Error: Can't resolve './theme.scss.css' in '/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/src/layout'
    at factory.create (/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/webpack/lib/Compilation.js:522:10)
    at factory (/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/webpack/lib/NormalModuleFactory.js:358:22)
    at resolver (/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/webpack/lib/NormalModuleFactory.js:118:21)
    at asyncLib.parallel (/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/webpack/lib/NormalModuleFactory.js:198:22)
    at /Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/neo-async/async.js:2817:7
    at /Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/neo-async/async.js:6783:13
    at normalResolver.resolve (/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/webpack/lib/NormalModuleFactory.js:188:25)
    at doResolve (/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/enhanced-resolve/lib/Resolver.js:181:12)
    at hook.callAsync (/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/enhanced-resolve/lib/Resolver.js:232:5)
    at _fn0 (eval at create (/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at resolver.doResolve (/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
    at hook.callAsync (/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/enhanced-resolve/lib/Resolver.js:232:5)
    at _fn0 (eval at create (/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at hook.callAsync (/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/enhanced-resolve/lib/Resolver.js:232:5)
    at _fn0 (eval at create (/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:12:1)
    at resolver.doResolve (/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
 @ . sync ^\.\/layout.*\.liquid$
 @ ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js
 @ multi ../node_modules/@shopify/slate-tools/tools/webpack/hot-client.js ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js

./layout/theme.liquid
Module build failed: ModuleNotFoundError: Module not found: Error: Can't resolve './theme.scss.css' in '/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/src/layout'
    at factory.create (/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/webpack/lib/Compilation.js:522:10)
    at factory (/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/webpack/lib/NormalModuleFactory.js:358:22)
    at resolver (/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/webpack/lib/NormalModuleFactory.js:118:21)
    at asyncLib.parallel (/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/webpack/lib/NormalModuleFactory.js:198:22)
    at /Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/neo-async/async.js:2817:7
    at /Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/neo-async/async.js:6783:13
    at normalResolver.resolve (/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/webpack/lib/NormalModuleFactory.js:188:25)
    at doResolve (/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/enhanced-resolve/lib/Resolver.js:181:12)
    at hook.callAsync (/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/enhanced-resolve/lib/Resolver.js:232:5)
    at _fn0 (eval at create (/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at resolver.doResolve (/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
    at hook.callAsync (/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/enhanced-resolve/lib/Resolver.js:232:5)
    at _fn0 (eval at create (/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at hook.callAsync (/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/enhanced-resolve/lib/Resolver.js:232:5)
    at _fn0 (eval at create (/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:12:1)
    at resolver.doResolve (/Users/narendrasisodiya/GitHub/we18/we18-theme-by-slate/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
 @ . sync ^\.\/layout.*\.liquid$
 @ ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js
 @ multi ../node_modules/@shopify/slate-tools/tools/webpack/hot-client.js ../node_modules/@shopify/slate-tools/tools/webpack/static-files-glob.js


⚠  It looks like you are about to upload the settings_data.json file.
   This can reset any theme setting customizations you have done in the
   Theme Editor. To always ignore uploading settings_data.json, add the
   following to your .env file:

      SLATE_IGNORE_FILES=/config/settings_data.json

   Or to disable this prompt, add the following to your slate.config.js file:

      slateTools: { promptSettings: false }
```

**Comment by we18** [comment]
I understand, that we can copy existing theme files into the src folder. So, Do we have starter repo for debut them?

**Comment by huguestennier** [comment]
Debut is not open-sourced, so there's no starter repo for it.

The two starting repo as of right now are [Starter Theme](https://github.com/Shopify/starter-theme/) and [Skeleton Theme](https://github.com/Shopify/skeleton-theme)
