### ISSUE TITLE
Error on yarn start:  Error: getaddrinfo ENOTFOUND , exit code 1

### ISSUE THREAD

**Issue by mikeriley131** [Shopify/slate#629]
### Problem
Slate failing with `exit code 1` on `yarn start`.

### Replication steps
`yarn start` - https://github.com/Shopify/slate/wiki/4.-Start-developing

### More Information
Node 10.4.0

```
✔  Compiled successfully in 5.069s!
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND maker-general.myshopify.com/ maker-general.myshopify.com/:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:50:26)
Emitted 'error' event at:
    at TLSSocket.socketErrorListener (_http_client.js:382:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by mikeriley131** [comment]
My bad, I was using the theme ID from the default Debut theme.

**Comment by jarvisjohnson** [comment]
I think the actual issue is you had a trailing slash in your url `maker-general.myshopify.com/`, see my answer in the issue referenced above.

**Comment by mikeriley131** [comment]
@jarvisjohnson Thanks, I'll test that next time I fire it up locally.
