### ISSUE TITLE
yarn start not working

### ISSUE THREAD

**Issue by marioloncarek** [Shopify/slate#649]
### Problem

Hello, i followed Slate install instructions from wiki, but yarn start (also tried npm start and npm run start) is not working, i get this error:

```
> starter-theme@1.0.0-alpha.1 start /Users/marioloncarek/Projects/###
> slate-tools start

(node:7962) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Server.setupListenHandle [as _listen2] (net.js:1346:14)
    at listenInCluster (net.js:1387:12)
    at Server.listen (net.js:1475:7)
    at DevServer.start (/Users/marioloncarek/Projects/###/node_modules/@shopify/slate-tools/tools/dev-server/index.js:32:17)
    at Object.<anonymous> (/Users/marioloncarek/Projects/###/node_modules/@shopify/slate-tools/cli/commands/start.js:151:11)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
Emitted 'error' event at:
    at emitErrorNT (net.js:1366:8)
    at process._tickCallback (internal/process/next_tick.js:178:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:697:11)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! starter-theme@1.0.0-alpha.1 start: `slate-tools start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the starter-theme@1.0.0-alpha.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

### Replication steps

run `yarn start`

**Comment by marioloncarek** [comment]
I managed to fix this issue. The issue is that something is listening to that port allready. To fix this find out what is listening to 8080. In terminal run `sudo lsof -i -n -P | grep TCP` . In list find out and kill the proces, for me it was `httpd`. 

### suggestion for improvement 

Its stupid that you have to listen to port 8080. That should be automatic or make it configurable via config. 

Thanks!

**Comment by t-kelly** [comment]
Related https://github.com/Shopify/slate/issues/553
