### ISSUE TITLE
npm start, Hostname/IP doesn't match certificate's altnames?

### ISSUE THREAD

**Issue by steffatstellaviecom** [Shopify/slate#666]
Getting started with Slate 1.x. Stumbling at "npm start" right after setting up the `.env` file. The theme is complied successfully, but followed by this error: Hostname/IP doesn't match certificate's altnames: "Host: EXAMPLE.myshopify.com. is not in the cert's altnames: DNS:*.myshopify.com, DNS:myshopify.com"

```
Error: Hostname/IP doesn't match certificate's altnames: "Host: example.myshopify.com. is not in the cert's altnames: DNS:*.myshopify.com, DNS:myshopify.com"
    at Object.checkServerIdentity (tls.js:223:17)
    at TLSSocket.<anonymous> (_tls_wrap.js:1111:29)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:639:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! starter-theme@1.0.0-alpha.1 start: `slate-tools start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the starter-theme@1.0.0-alpha.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by steffatstellaviecom** [comment]
Solved. Just a stupid tying error; my bad.
