### ISSUE TITLE
WSL Ubuntu 18.04 / Win10  -- Fails on fresh install

### ISSUE THREAD

**Issue by zgjonbalaj** [Shopify/slate#667]
### Problem

Fresh install of NVM, Node 10.6.0

### Replication steps

1. Install WSL, Ubuntu 18.04, NVM, Node & Yarn
2. Run 'yarn create slate-theme mythemename'

### More Information

`[4/4] Building fresh packages...
[-/6] ⠠ waiting...
[-/6] ⠠ waiting...
[-/6] ⠠ waiting...
[-/6] ⠠ waiting...
error /mnt/d/Code/Projects/hausextension/node_modules/pngquant-bin: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments:
Directory: /mnt/d/Code/Projects/hausextension/node_modules/pngquant-bin
Output:
⚠ The `/mnt/d/Code/Projects/hausextension/node_modules/pngquant-bin/vendor/pngquant` binary doesn't seem to work correctly
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✔ pngquant pre-build test passed successfully
  ✖ Error: pngquant failed to build, make sure that libpng-dev is installed

(node:1362) UnhandledPromiseRejectionWarning: Error: Command failed: yarnpkg
    at makeError (/home/zgjonbalaj/.config/yarn/global/node_modules/execa/index.js:169:9)
    at Promise.all.then.arr (/home/zgjonbalaj/.config/yarn/global/node_modules/execa/index.js:274:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1362) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:1362) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 326.52s.`

**Comment by zgjonbalaj** [comment]
Checked for libpng-dev, installed it, same issue.

Reading package lists... Done
Building dependency tree
Reading state information... Done
libpng-dev is already the newest version (1.6.34-1).
0 upgraded, 0 newly installed, 0 to remove and 98 not upgraded.

**Comment by YogiZoli** [comment]
Do you have any solution for this? Thanks

**Comment by lloydstubber** [comment]
@YogiZoli @zgjonbalaj -- I'm using an older version of Ubuntu but this is my work around: https://github.com/Shopify/slate/issues/570

**Comment by dustinboettcher** [comment]
Here is what works for me (same Version) - cp paste each line after a fresh wsl install. If you already installed most of it line 2 might be interesting for you

sudo apt update && sudo apt -y upgrade
sudo apt install -y build-essential libssl-dev libpng-dev
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt update && sudo apt install -y nodejs
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt update && sudo apt install yarn
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
exit
source ~/.profile
sudo chown -R $USER /usr/lib/node_modules/

**Comment by axlc** [comment]
@dustinboettcher -- I'm on a machine running Ubuntu 18.04, but I was experiencing these same issues.

The instructions you gave worked very well for me. I already had yarn installed, but uninstalling it before running your commands fixed the issues for me.

Thanks!

**Comment by t-kelly** [comment]
Was able to replicate this as well. The missing piece that @dustinboettcher was able to nail was:
```
sudo apt update && sudo apt -y upgrade
sudo apt install -y build-essential libssl-dev libpng-dev
```

Going to add this to the docs!

**Comment by zgjonbalaj** [comment]
@t-kelly Yeah scoop seems to be a great alternative to installing all of the dev environment tools on Windows. Very similar to brew if your familiar with that. Somehow that build just worked right out of the box but i did uninstall everything (php, python, nodejs, npm etc) before running scoop.

**Comment by ChariseWalraven** [comment]
This works for me as well, although I'm using zsh and oh-my-zsh. I've found that it doesn't work when doing a fresh install on the zsh shell, but that it does work in regular bash in WSL, which is a little weird.

**Comment by tracy-codes** [comment]
Figured I'd chime in here. If you're running into SSL issues still on Ubuntu/Linux, I opened #1083  to update the docs with a Linux-specific `ssl-check` function. I've tested on a few different versions of Ubuntu and so far it seems to work.

Feel free to test it out and let me know if you run into any issues, I'll work to update the new `ssl-check` function if any errors happen on other Linux distros.

**Comment by martinseanhunt** [comment]
Has anyone currently got this working on ubuntu? I'm running in to issues with node-sass

**Comment by zgjonbalaj** [comment]
I've given up on this and have gone back to just using themekit to download and upload files manually. Not the integrated workflow I was hoping for but then again Shopify has dropped all support on this. Hopefully we get to see a fully working integrated environment in the future.
