### ISSUE TITLE
Slate not installing at all

### ISSUE THREAD

**Issue by adamrasheed** [Shopify/slate#760]
### Problem

Why I create to create a new slate project with `yarn create slate-theme theme-name`,
I get the following error in my terminal:
```
error Couldn't find package "@shopify/slate-env@1.0.0-beta.8" required by "@shopify/slate-analytics@1.0.0-beta.8" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
Error: Couldn't find package "@shopify/slate-env@1.0.0-beta.8" required by "create-slate-theme" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.9.4/libexec/lib/cli.js:243:66)
    at new MessageError (/usr/local/Cellar/yarn/1.9.4/libexec/lib/cli.js:272:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.9.4/libexec/lib/cli.js:38988:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.9.4/libexec/lib/cli.js:92:30)
    at /usr/local/Cellar/yarn/1.9.4/libexec/lib/cli.js:105:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error: Couldn't find package "@shopify/slate-config@1.0.0-beta.8" required by "@shopify/slate-rc@1.0.0-beta.8" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.9.4/libexec/lib/cli.js:243:66)
    at new MessageError (/usr/local/Cellar/yarn/1.9.4/libexec/lib/cli.js:272:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.9.4/libexec/lib/cli.js:38988:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.9.4/libexec/lib/cli.js:92:30)
    at /usr/local/Cellar/yarn/1.9.4/libexec/lib/cli.js:105:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

### Replication steps
- My node version: 8.11.3
- Npm version: 5.6.0 
- yarn version: 1.9.4

Creating a new project should hopefully replicate the process?

I've also tried installing the npm package `npm i create-slate-theme` and get the following error:
```
npm ERR! code E404
npm ERR! 404 Not Found: @shopify/slate-env@1.0.0-beta.8
```

Please help!

**Comment by t-kelly** [comment]
Working fine for me. Can't reproduce this.

Check your `~/.npmrc` file? You might be referencing another NPM registry? That can bit me in the ass once or twice before.

Otherwise not much I can do to help. Sorry!

**Comment by t-kelly** [comment]
Does it exist? Is there anything in it? If so, it's could be producing non default NPM behaviour.

**Comment by adamrasheed** [comment]
Yeah it exists because I believe using font-aweome installed it.
