### ISSUE TITLE
Unhandled exception: socket hang up.

### ISSUE THREAD

**Issue by GlueDigiStu** [Shopify/slate#860]
### Problem

Unhandled exception if connection is lost during upload.

```
(node:90356) UnhandledPromiseRejectionWarning: Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1148:19)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at TLSSocket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
(node:90356) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, orby rejecting a promise which was not handled with .catch(). (rejection id: 16)
```

### Replication steps

Update any file while `watch` is running, and ensure you're connected to an unreliable hotel connection during peak time to ensure maximum chance that the upload fails. 

### More Information

Would be best to try to repeat the upload in my personal scenario, I'd hope that the upload could be queued to try again after a network check, but a better error message would be great too to know which file failed so it can be checked to ensure no problems.

**Comment by reco** [comment]
same here any solution?

**Comment by codeams** [comment]
Same thing.
